clicking sign with microsoft loads for 2 seconds and nothing happens. i stay in the login screen.
then after few seconds im being moved to send event screen with this message:
Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it. {$$typeof: ..., render: function Activity} ^^^^^^^^^^^^^^^^^